image: docker:19.03.12

services:
  - docker:19.03.12-dind

stages:
  - build
  - push

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  DOCKERHUB_USERNAME: your_dockerhub_username
  DOCKERHUB_PASSWORD: your_dockerhub_password
  DOCKERHUB_REPO: django-pg-docker-tutorial
  IMAGE_TAG: $CI_COMMIT_SHA

before_script:
  - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD

build:
  stage: build
  script:
    - docker build -t $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:$IMAGE_TAG .
  artifacts:
    paths:
      - ./Dockerfile

push:
  stage: push
  script:
    - docker push $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:$IMAGE_TAG